// Import the MIPS parser
// The parser is generated by Jison and uses CommonJS exports

import { MIPS_EXCEPTION_VECTOR } from '../core/constants';
import type { Instruction } from '../core/encoding';

/** MARS `.ktext` load / exception vector (re-export for callers). */
export const KTEXT_LOAD_ADDRESS = MIPS_EXCEPTION_VECTOR;

// Type definition for the parser
interface Parser {
  parse(input: string): any;
  yy?: any;
}

let parser: Parser | null = null;

// Dynamically load the parser
async function loadParser() {
  if (!parser) {
    try {
      // Try to import the parser module (CommonJS)
      // @ts-ignore - Parser is generated CommonJS module
      const parserModule: any = await import('../../parser/mips.js');
      
      // Try different ways to access the parser
      if (parserModule.parser) {
        parser = parserModule.parser;
      } else if (parserModule.default && parserModule.default.parser) {
        parser = parserModule.default.parser;
      } else if (parserModule.default) {
        parser = parserModule.default;
      } else if (typeof parserModule.parse === 'function') {
        // If we have a parse function directly, create a parser-like object
        parser = parserModule;
      } else {
        console.error('Available exports:', parserModule);
        throw new Error('Could not find parser in module exports');
      }
      
    } catch (error) {
      console.error('Failed to load MIPS parser:', error);
      throw new Error(`MIPS parser could not be loaded: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }
  return parser;
}

/**
 * MIPSParser class for parsing and processing MIPS assembly code
 */
export class MIPSParser {
  parser: Parser | null;
  symbols: Map<string, number>;
  instructions: any[];
  dataAddr: number;
  textAddr: number;
  data: number[];
  text: any[];
  /** Byte offsets of .text labels (same encoding as resolveBranchAndJumpTargets) while expanding pseudos */
  private textLabelAddrsForExpand?: Map<string, number>;

  constructor(dataAddr = 0x00000000, textAddr = 0x00400000) {
    this.parser = null;
    this.symbols = new Map(); // Symbol table for labels
    this.instructions = [];
    this.dataAddr = dataAddr;
    this.textAddr = textAddr;
    this.data = [];
    this.text = [];
  }

  /**
   * Initialize the parser (loads it asynchronously)
   */
  async initParser(): Promise<Parser> {
    if (!this.parser) {
      this.parser = await loadParser();
    }
    if (!this.parser) {
      throw new Error('Parser initialization failed');
    }
    return this.parser;
  }

  /**
   * Parse MIPS assembly code
   */
  async parse(input: string): Promise<any> {
    await this.initParser();
    let normalized = input
      .replace(/^\uFEFF/, '')
      .replace(/\r\n/g, '\n')
      .replace(/\r/g, '\n');
    if (!normalized.endsWith('\n')) {
      normalized += '\n';
    }
    try {
      const program = this.parser!.parse(normalized);
      return program;
    } catch (error: any) {
      throw new Error(`Parse error: ${error.message}`);
    }
  }

  /**
   * Read data section and populate symbol table
   */
  readDataSymbols(data: any[]): void {
    if (!data) return;
    
    data.forEach(statement => {
      if (statement.type === 'asciiz') {
        this.symbols.set(statement.label, this.dataAddr);

        let string = statement.string;
        // Remove the quotes
        string = string.replace(/^"|"$/g, '');
        // Write every byte of the string to the data section
        for (let i = 0; i < string.length; i++) {
          this.data.push(string.charCodeAt(i));
        }
        this.data.push(0x00); // Null terminator
        this.dataAddr += string.length + 1;
      } else if (statement.type === 'word') {
        this.symbols.set(statement.label, this.dataAddr);
        this.dataAddr += 4 * statement.values.length;
        // Write every word to the data section
        for (let i = 0; i < statement.values.length; i++) {
          this.data.push(statement.values[i]);
        }
      }
    });
  }

  /**
   * Expand pseudo-instructions to real MIPS instructions
   */
  /**
   * Word count after pseudo expansion for one AST text statement (must match expandPseudo).
   * prevTextLabels: label → byte offset from previous layout iteration (for forward refs in la).
   */
  private statementExpandedWordCount(stmt: any, prevTextLabels: Map<string, number>): number {
    if (!stmt || stmt.type === 'globl') return 0;
    if (stmt.type !== 'pseudo') return 1;
    if (stmt.op === 'move') return 1;
    if (stmt.op === 'li') {
      if (typeof stmt.immediate !== 'undefined') {
        const imm = stmt.immediate as number;
        if (imm >= -32768 && imm <= 32767) return 1;
        const lower = imm & 0xffff;
        return lower !== 0 ? 2 : 1;
      }
      if (typeof stmt.symbol !== 'undefined') return 2;
      return 1;
    }
    if (stmt.op === 'la') {
      let addr: number | undefined;
      if (typeof stmt.symbol !== 'undefined') {
        addr = this.symbols.get(stmt.symbol);
        if (addr === undefined) addr = prevTextLabels.get(stmt.symbol);
        if (addr === undefined) return 2;
      } else if (typeof stmt.immediate !== 'undefined') {
        addr = stmt.immediate as number;
      } else {
        return 1;
      }
      return (addr & 0xffff) !== 0 ? 2 : 1;
    }
    return 1;
  }

  private static mapsEqualNumber(a: Map<string, number>, b: Map<string, number>): boolean {
    if (a.size !== b.size) return false;
    for (const [k, v] of b) {
      if (a.get(k) !== v) return false;
    }
    return true;
  }

  /**
   * Compute byte addresses of text labels before expansion so li/la can reference them.
   * Iterates until la(symbol) sizes stabilize w.r.t. label addresses.
   * @param byteBase Absolute byte PC of the first instruction in this segment.
   * @param reservedNames Labels already taken in another segment (.text vs .ktext).
   */
  private convergeTextLabelPlacements(
    text: any[],
    byteBase: number,
    reservedNames: Set<string>,
  ): Map<string, number> {
    let prev = new Map<string, number>();
    for (let iter = 0; iter < 32; iter++) {
      let pc = byteBase;
      const next = new Map<string, number>();
      for (const stmt of text) {
        if (!stmt || stmt.type === 'globl') continue;
        if (stmt.label) {
          const name = stmt.label as string;
          if (this.symbols.has(name)) {
            throw new Error(`Label ${name} conflicts with a data or existing symbol`);
          }
          if (reservedNames.has(name) || next.has(name)) {
            throw new Error(`Duplicate text label: ${name}`);
          }
          next.set(name, pc);
        }
        pc += this.statementExpandedWordCount(stmt, prev) * 4;
      }
      if (MIPSParser.mapsEqualNumber(prev, next)) {
        return next;
      }
      prev = next;
    }
    throw new Error('Text section layout did not stabilize (label resolution)');
  }

  expandPseudoInstructions(text: any[]): any[] {
    if (!text) return [];
    
    const expanded: any[] = [];
    text.forEach(statement => {
      if (statement.type === 'pseudo') {
        expanded.push(...this.expandPseudo(statement));
      } else if (statement.type === 'globl') {
        // Skip .globl directives
      } else {
        expanded.push(statement);
      }
    });
    return expanded;
  }

  /**
   * Expand a single pseudo-instruction
   */
  expandPseudo(stmt: any): any[] {
    const expanded: any[] = [];
    
    if (stmt.op === 'li') {
      // li rt, immediate
      const rt = stmt.rt;
      if (typeof rt === 'undefined') {
        throw new Error('Unknown register in li');
      }

      if (typeof stmt.immediate !== 'undefined') {
        // li rt, immediate
        const imm = stmt.immediate;
        
        // Check if immediate fits in 16 bits (signed)
        if (imm >= -32768 && imm <= 32767) {
          expanded.push({ 
            from_id: stmt.id, 
            type: 'i_type', 
            op: 'addiu', 
            rt: rt, 
            rs: 0, 
            immediate: imm 
          });
        } else {
          // Need lui + ori for larger values
          const upper = (imm >>> 16) & 0xffff;
          const lower = imm & 0xffff;
          
          expanded.push({ 
            from_id: stmt.id, 
            type: 'i_type', 
            op: 'lui', 
            rt: rt, 
            immediate: upper 
          });
          
          if (lower !== 0) {
            expanded.push({ 
              from_id: stmt.id, 
              type: 'i_type', 
              op: 'ori', 
              rt: rt, 
              rs: rt, 
              immediate: lower 
            });
          }
        }
      } else if (typeof stmt.symbol !== 'undefined') {
        // li rt, symbol
        const addr =
          this.symbols.get(stmt.symbol) ?? this.textLabelAddrsForExpand?.get(stmt.symbol);
        if (typeof addr === 'undefined') {
          throw new Error('Undefined label: ' + stmt.symbol);
        }

        // Load upper 16 bits
        expanded.push({ 
          from_id: stmt.id, 
          type: 'i_type', 
          op: 'lui', 
          rt: rt, 
          immediate: (addr >>> 16) & 0xffff 
        });

        // Load lower 16 bits
        expanded.push({ 
          from_id: stmt.id, 
          type: 'i_type', 
          op: 'ori', 
          rt: rt, 
          rs: rt, 
          immediate: addr & 0xffff 
        });
      } else {
        throw new Error('Unsupported pseudo-instruction: ' + stmt.op);
      }
    } else if (stmt.op === 'la') {
      // la rt, symbol or immediate
      const rt = stmt.rt;
      if (typeof rt === 'undefined') {
        throw new Error('Unknown register in la');
      }

      let addr;
      if (typeof stmt.symbol !== 'undefined') {
        addr =
          this.symbols.get(stmt.symbol) ?? this.textLabelAddrsForExpand?.get(stmt.symbol);
        if (typeof addr === 'undefined') {
          throw new Error('Undefined label: ' + stmt.symbol);
        }
      } else if (typeof stmt.immediate !== 'undefined') {
        addr = stmt.immediate;
      } else {
        throw new Error('la requires symbol or immediate');
      }

      // Load upper 16 bits
      expanded.push({ 
        from_id: stmt.id, 
        type: 'i_type', 
        op: 'lui', 
        rt: rt, 
        immediate: (addr >>> 16) & 0xffff 
      });

      // Load lower 16 bits
      const lower = addr & 0xffff;
      if (lower !== 0) {
        expanded.push({ 
          from_id: stmt.id, 
          type: 'i_type', 
          op: 'ori', 
          rt: rt, 
          rs: rt, 
          immediate: lower 
        });
      }
    } else if (stmt.op === 'move') {
      // move rd, rs -> addiu rd, rs, 0
      const rd = stmt.rd;
      const rs = stmt.rs;
      if (typeof rd === 'undefined' || typeof rs === 'undefined') {
        throw new Error('Unknown register in move');
      }
      expanded.push({ 
        from_id: stmt.id, 
        type: 'i_type', 
        op: 'addiu', 
        rt: rd, 
        rs: rs, 
        immediate: 0 
      });
    } else {
      throw new Error('Unsupported pseudo-instruction: ' + stmt.op);
    }

    if (stmt.label && expanded.length > 0) {
      expanded[0] = { ...expanded[0], label: stmt.label };
    }

    return expanded;
  }

  private static readonly BRANCH_OPS = new Set([
    'beq',
    'bne',
    'blez',
    'bgtz',
    'bltz',
    'bgez',
    'bltzal',
    'bgezal',
  ]);

  /**
   * Assign byte addresses to text labels and patch branch/jump immediates.
   * @param byteBase Absolute byte PC of index 0 in `text`.
   * @param extraTextLabels Labels from another segment (e.g. user `.text` when resolving `.ktext`).
   */
  resolveBranchAndJumpTargets(
    text: any[],
    byteBase: number = 0,
    extraTextLabels?: Map<string, number>,
  ): any[] {
    const textLabels = new Map<string, number>();

    text.forEach((instr, i) => {
      if (!instr || !instr.label) return;
      const name = instr.label as string;
      if (textLabels.has(name)) {
        throw new Error(`Duplicate text label: ${name}`);
      }
      if (this.symbols.has(name)) {
        throw new Error(`Label ${name} conflicts with a data or existing symbol`);
      }
      if (extraTextLabels?.has(name)) {
        throw new Error(`Duplicate text label: ${name}`);
      }
      textLabels.set(name, byteBase + i * 4);
    });

    const lookupAddr = (name: string): number | undefined => {
      if (textLabels.has(name)) return textLabels.get(name);
      if (extraTextLabels?.has(name)) return extraTextLabels.get(name);
      return this.symbols.get(name);
    };

    return text.map((instr, i) => {
      if (!instr) return instr;
      const copy = { ...instr };
      const byteAddr = byteBase + i * 4;
      const op = String(instr.op || '').toLowerCase();

      if (MIPSParser.BRANCH_OPS.has(op) && instr.target !== undefined) {
        if (typeof instr.target === 'string') {
          const targetAddr = lookupAddr(instr.target);
          if (typeof targetAddr === 'undefined') {
            throw new Error(`Undefined label: ${instr.target}`);
          }
          const offsetWords = (targetAddr - (byteAddr + 4)) / 4;
          if (!Number.isInteger(offsetWords)) {
            throw new Error(`Invalid branch offset for label: ${instr.target}`);
          }
          if (offsetWords < -32768 || offsetWords > 32767) {
            throw new Error(`Branch offset out of 16-bit range for label: ${instr.target}`);
          }
          copy.immediate = offsetWords;
          delete copy.target;
        } else if (typeof instr.target === 'number') {
          copy.immediate = instr.target;
          delete copy.target;
        }
      }

      if ((op === 'j' || op === 'jal') && typeof instr.target === 'string') {
        const targetAddr = lookupAddr(instr.target);
        if (typeof targetAddr === 'undefined') {
          throw new Error(`Undefined label: ${instr.target}`);
        }
        copy.target = (targetAddr >>> 2) & 0x03ffffff;
      }

      return copy;
    });
  }

  private static isExecutableInstruction(instr: any): boolean {
    return (
      !!instr &&
      instr.type &&
      (instr.type === 'r_type' ||
        instr.type === 'i_type' ||
        instr.type === 'j_type' ||
        instr.type === 'cop0_type' ||
        instr.type === 'special')
    );
  }

  /**
   * Process complete MIPS program
   */
  async processProgram(input: string): Promise<any> {
    const ast = await this.parse(input);

    if (ast.data?.length) {
      this.readDataSymbols(ast.data);
    }

    const instructionWordMap = new Map<number, Instruction>();
    let userExpanded: any[] = [];
    const reservedAcrossSegments = new Set<string>();
    let userLabelMapForExpand = new Map<string, number>();

    if (ast.text?.length) {
      userLabelMapForExpand = this.convergeTextLabelPlacements(ast.text, 0, new Set());
      for (const k of userLabelMapForExpand.keys()) {
        reservedAcrossSegments.add(k);
      }
      this.textLabelAddrsForExpand = userLabelMapForExpand;
      try {
        userExpanded = this.expandPseudoInstructions(ast.text);
        userExpanded = this.resolveBranchAndJumpTargets(userExpanded, 0);
      } finally {
        this.textLabelAddrsForExpand = undefined;
      }
      userExpanded.forEach((ins, i) => {
        if (MIPSParser.isExecutableInstruction(ins)) {
          instructionWordMap.set(i, ins);
        }
      });
    }

    this.text = userExpanded;
    const userTextWordCount = userExpanded.filter(MIPSParser.isExecutableInstruction).length;

    const ktextBlocks = ast.ktextBlocks ?? [];
    let ktextCursor = MIPS_EXCEPTION_VECTOR;
    for (const block of ktextBlocks) {
      const addr = block.address;
      if (addr != null && (addr >>> 0) !== (ktextCursor >>> 0)) {
        throw new Error(
          `Expected .ktext at 0x${ktextCursor.toString(16)}, got 0x${(addr >>> 0).toString(16)}`,
        );
      }
      const stmts = block.statements ?? [];
      const kLabelMap = this.convergeTextLabelPlacements(stmts, ktextCursor, reservedAcrossSegments);
      for (const k of kLabelMap.keys()) {
        reservedAcrossSegments.add(k);
      }
      const combinedLabels = new Map([...userLabelMapForExpand, ...kLabelMap]);
      this.textLabelAddrsForExpand = combinedLabels;
      let kExpanded: any[];
      try {
        kExpanded = this.expandPseudoInstructions(stmts);
        kExpanded = this.resolveBranchAndJumpTargets(kExpanded, ktextCursor, userLabelMapForExpand);
      } finally {
        this.textLabelAddrsForExpand = undefined;
      }
      const startWord = (ktextCursor >>> 2) >>> 0;
      kExpanded.forEach((ins, i) => {
        if (MIPSParser.isExecutableInstruction(ins)) {
          instructionWordMap.set(startWord + i, ins);
        }
      });
      ktextCursor += kExpanded.filter(MIPSParser.isExecutableInstruction).length * 4;
    }

    return {
      ast,
      symbols: this.symbols,
      data: this.data,
      text: this.text,
      instructionWordMap,
      userTextWordCount,
    };
  }

  /**
   * Reset parser state
   */
  reset() {
    this.symbols.clear();
    this.instructions = [];
    this.data = [];
    this.text = [];
    this.textLabelAddrsForExpand = undefined;
    this.dataAddr = 0x00000000;
    this.textAddr = 0x00400000;
  }
}

// Legacy async function for backward compatibility
export async function parseMIPSCode(code: string): Promise<any> {
  try {
    const p = await loadParser();
    const ast = p!.parse(code);
    return ast;
  } catch (error: any) {
    throw new Error(`Parse error: ${error.message}`);
  }
}

// Synchronous version that assumes parser is loaded
export function parseMIPSCodeSync(code: string): any {
  if (!parser) {
    throw new Error('Parser not loaded. Call parseMIPSCode first.');
  }
  try {
    const ast = parser.parse(code);
    return ast;
  } catch (error: any) {
    throw new Error(`Parse error: ${error.message}`);
  }
}

